version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.3

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: aws-rds-profile
      - run:
          name: Print AWS CLI version
          command: aws --version
      - run:
          name: Set up virtual environment
          command: | 
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run migrations
          command: |
            . venv/bin/activate
            echo $AWS_DB_HOST
            python app/manage.py migrate
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest tests/
            
workflows:
  build_and_test:
    jobs:
      - build:
          context: aws_dev