version: 2.1

orbs:
  aws-rds: ware2go/aws-rds@1.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - aws-rds/start:
          rds-instance-identifier: "revbot"
          aws-region: "eu-north-1b"
          db-name: "revbot"
          db-username: "Helmwill"
          db-password: "Tradingbot9"
      - run:
          name: Set up virtual environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run migrations
          command: |
            . venv/bin/activate
            python manage.py migrate

workflows:
  build_and_test:
    jobs:
      - build
