# Generated by Django 5.0.6 on 2024-06-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField()),
                ("low", models.FloatField()),
                ("high", models.FloatField()),
                ("open", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.FloatField()),
            ],
        ),
    ]
